import * as fs from 'node:fs';
import * as path from 'node:path';
import { tmpdir } from 'node:os';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { RepoReleases } from '../octo.js';

vi.mock('../octo.js', () => ({
  createOctokit: vi.fn(() => ({})),
  findExistingChangelogPR: vi.fn(),
  listReleases: vi.fn(),
}));

const { listReleases } = await import('../octo.js');
const { analyze, writePreview } = await import('../shared/github.js');
const mockListReleases = vi.mocked(listReleases);

const tmpRoots: string[] = [];
const originalConfigPath = process.env.CHANGELOG_CONFIG_PATH;

function makeRepoRoot(): string {
  const repoRoot = fs.mkdtempSync(path.join(tmpdir(), 'changelog-e2e-'));
  tmpRoots.push(repoRoot);
  fs.mkdirSync(path.join(repoRoot, 'changelog', 'entries'), {
    recursive: true,
  });
  fs.writeFileSync(
    path.join(repoRoot, 'changelog', 'entries', '2026-04-15-existing.md'),
    `---
title: 'Existing'
categories: ['MCP']
---

Existing changelog entry.

{/* truncate */}

## Changes

- Existing changelog entry.
`,
  );
  return repoRoot;
}

function writeConfig(repoRoot: string): string {
  const configPath = path.join(repoRoot, 'config.yml');
  fs.writeFileSync(
    configPath,
    `owner: gleanwork
baseBranch: main
repos:
  - { repo: api-client-go, category: 'API Clients', parser: speakeasy }
  - { repo: glean-indexing-sdk, category: 'Glean Indexing SDK', parser: commitizen }
  - { repo: mcp-server, category: 'MCP', parser: lerna-changelog }
  - { repo: api-client-typescript, category: 'API Clients', parser: speakeasy }
  - { repo: api-client-java, category: 'API Clients', parser: speakeasy }
  - { repo: broken-repo, category: 'MCP', parser: plain }
`,
  );
  return configPath;
}

function release(
  repo: string,
  tag: string,
  publishedAt: string,
  body: string,
): RepoReleases[number] {
  return {
    tag_name: tag,
    published_at: `${publishedAt}T12:00:00Z`,
    html_url: `https://github.com/gleanwork/${repo}/releases/tag/${tag}`,
    url: `https://api.github.com/repos/gleanwork/${repo}/releases/tags/${tag}`,
    body,
  } as unknown as RepoReleases[number];
}

function speakeasyBody(): string {
  return `# Generated by Speakeasy CLI

## Go SDK Changes:
* \`Glean.Client.Search.RetrieveFeed()\`:  \`response.Results[].PrimaryEntry.Workflow.Workflow.LastDraftSavedAt\` **Added**
* \`Glean.Client.Insights.Retrieve()\`:  \`response.AgentsResponse\` **Changed**

Generated with [Speakeasy CLI 1.761.3](https://github.com/speakeasy-api/speakeasy/releases)`;
}

function emptySpeakeasyBody(): string {
  return `# Generated by Speakeasy CLI

## 2026-04-20 17:34:02
### Changes
Based on:
- OpenAPI Doc 0.9.0
### Generated
- [typescript v0.14.19] .

Publishing Completed`;
}

function commitizenBody(): string {
  return `## v1.0.0b2

### Feat

- add bulk indexing helpers (#14)

### Fix

- handle document retry errors (#15)

**Full Changelog**: https://github.com/gleanwork/glean-indexing-sdk/compare/v1.0.0b1...v1.0.0b2`;
}

function lernaBody(): string {
  return `#### :rocket: Enhancement

- [#123](https://github.com/gleanwork/mcp-server/pull/123) feat: add OAuth callback validation (@octocat)

#### :bug: Bug Fix

- [#124](https://github.com/gleanwork/mcp-server/pull/124) fix: preserve existing server config entries (@octocat)
`;
}

function assertNormalizedMdx(content: string): void {
  expect(content).toMatch(/^---\ntitle: '.+'\ncategories: \['.+']\n---\n/);
  expect(content.match(/\{\/\*\s*truncate\s*\*\/\}/g)).toHaveLength(1);
  expect(content).toContain('## Changes');
  expect(content).toContain('## Source');
  expect(content).not.toMatch(/\p{Extended_Pictographic}/u);
  expect(content).not.toMatch(
    /:(rocket|bug|house|memo|warning|lock|boom|sparkles|white_check_mark|x):/i,
  );
  expect(content.split('{/* truncate */}')[0]).not.toMatch(
    /\.\s+-\s+(Added|Changed|Fixed|Removed)/i,
  );
}

afterEach(() => {
  process.env.CHANGELOG_CONFIG_PATH = originalConfigPath;
  mockListReleases.mockReset();
  for (const root of tmpRoots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

describe('changelog generation end-to-end', () => {
  it('analyzes configured repos, normalizes entries, reports skips/errors, and writes a preview', async () => {
    const repoRoot = makeRepoRoot();
    process.env.CHANGELOG_CONFIG_PATH = writeConfig(repoRoot);

    const releasesByRepo: Record<string, RepoReleases> = {
      'api-client-go': [
        release('api-client-go', 'v0.11.99', '2026-04-16', speakeasyBody()),
      ] as RepoReleases,
      'glean-indexing-sdk': [
        release(
          'glean-indexing-sdk',
          'v1.0.0b2',
          '2026-04-17',
          commitizenBody(),
        ),
      ] as RepoReleases,
      'mcp-server': [
        release('mcp-server', 'v0.10.2', '2026-04-18', lernaBody()),
      ] as RepoReleases,
      'api-client-typescript': [
        release(
          'api-client-typescript',
          'v0.14.19',
          '2026-04-19',
          emptySpeakeasyBody(),
        ),
      ] as RepoReleases,
      'api-client-java': [
        release('api-client-java', 'v0.12.36', '2026-04-10', speakeasyBody()),
      ] as RepoReleases,
    };

    mockListReleases.mockImplementation(async (_octokit, params) => {
      if (params.repo === 'broken-repo') {
        throw new Error('GitHub API unavailable');
      }
      return releasesByRepo[params.repo] || ([] as unknown as RepoReleases);
    });

    const analyzed = await analyze(repoRoot);
    const previewDir = writePreview(analyzed, repoRoot);

    expect(analyzed.latestChangelogEntryDate).toBe('2026-04-15');
    expect(analyzed.files).toHaveLength(3);
    expect(analyzed.report.stats).toMatchObject({
      totalProcessed: 6,
      includedCount: 3,
      skippedCount: 2,
      errorCount: 1,
    });

    const byRepo = new Map(
      analyzed.files.map((file) => [file.metadata?.repo, file]),
    );
    expect(byRepo.get('api-client-go')?.metadata?.parser).toBe('speakeasy');
    expect(byRepo.get('glean-indexing-sdk')?.metadata?.parser).toBe(
      'commitizen',
    );
    expect(byRepo.get('mcp-server')?.metadata?.parser).toBe('lerna-changelog');

    for (const file of analyzed.files) {
      assertNormalizedMdx(file.content);
      expect(fs.existsSync(path.join(previewDir, file.path))).toBe(true);
    }

    expect(byRepo.get('api-client-go')?.content).toContain(
      'Added `response.Results[]',
    );
    expect(byRepo.get('glean-indexing-sdk')?.content).toContain(
      'Add bulk indexing helpers',
    );
    expect(byRepo.get('mcp-server')?.content).toContain(
      'Add OAuth callback validation',
    );
    expect(byRepo.get('mcp-server')?.content).not.toContain(':rocket:');

    expect(analyzed.report.skipped).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          repo: 'api-client-typescript',
          tag: 'v0.14.19',
          emptyOrNoop: true,
        }),
        expect.objectContaining({
          repo: 'api-client-java',
          olderThanLatest: true,
        }),
      ]),
    );
    expect(analyzed.report.errors).toEqual([
      expect.objectContaining({
        repo: 'broken-repo',
        stage: 'fetch',
        reason: 'GitHub API unavailable',
      }),
    ]);

    expect(analyzed.pr.body).toContain('## Generated entries');
    expect(analyzed.pr.body).toContain(
      '| Repo/source | Tag/date | Parser | Entry | Source links |',
    );
    expect(analyzed.pr.body).toContain(
      '| api-client-go | v0.11.99 | speakeasy |',
    );
    expect(analyzed.pr.body).toContain(
      '| Repo/tag | Reason | Classification |',
    );
    expect(analyzed.pr.body).toContain('empty/no-op');
    expect(analyzed.pr.body).toContain('older than latest entry');
    expect(analyzed.pr.body).toContain(
      '| Repo/tag | Stage | Actionable message |',
    );
    expect(analyzed.pr.body).toContain(
      '| broken-repo | fetch | GitHub API unavailable |',
    );
  });
});
