import { describe, expect, it } from 'vitest';
import type { NormalizedRelease, RawRelease } from '../types.js';
import { normalizeRelease } from '../normalizers/index.js';
import { truncateSentence } from '../normalizers/utils.js';
import { renderNormalizedRelease } from '../normalized-renderer.js';
import { renderChangelogEntry } from '../template.js';
import { validateRenderedEntry } from '../validators.js';

function release(overrides: Partial<RawRelease>): RawRelease {
  return {
    owner: 'gleanwork',
    repo: 'mcp-config',
    tag: 'v1.0.0',
    url: 'https://github.com/gleanwork/mcp-config/releases/tag/v1.0.0',
    publishedAt: '2026-04-01',
    body: '',
    category: 'MCP',
    ...overrides,
  };
}

function renderEntry(normalized: NormalizedRelease): string {
  const rendered = renderNormalizedRelease(normalized);
  return renderChangelogEntry({
    repoRoot: process.cwd(),
    title: `${normalized.release.repo} ${normalized.release.tag}`,
    categories: [normalized.release.category],
    summary: rendered.summary,
    detailedContent: rendered.detailedContent,
  });
}

function expectNormalizedEntry(content: string): void {
  expect(validateRenderedEntry(content).valid).toBe(true);
  expect(content).not.toMatch(/\p{Extended_Pictographic}/u);
  expect(content).not.toMatch(/:[a-z0-9_+-]+:/i);
  expect(content.match(/\{\/\*\s*truncate\s*\*\/\}/g)).toHaveLength(1);
  expect(content).toContain('## Changes');
  expect(content).toContain('## Source');
  expect(content).not.toMatch(/\.\s+-\s+Added/i);
}

describe('normalized release parsing and rendering', () => {
  it('clips long summaries without terminal ellipses or dangling connectors', () => {
    const summary = truncateSentence(
      'Added lastDraftSavedAt workflow field to search feed results in glean.client.search.retrieveFeed() and statuses filter field to governance findings export endpoints glean.governance.createfindingsexport() and glean.governance.listfindingsexports().',
    );

    expect(summary).not.toMatch(/\.\.\.$/);
    expect(summary).not.toMatch(/\b(and|or|to|on|in|for|from|with)\.$/i);
    expect(summary).toMatch(/[.!?]$/);
  });

  it('normalizes release-it/lerna changelog entries without leaking upstream emoji headings', () => {
    const normalized = normalizeRelease(
      release({
        repo: 'mcp-config',
        tag: 'v5.0.0',
        body: `#### :rocket: Enhancement

- [#123](https://github.com/gleanwork/mcp-config/pull/123) feat: add server URL schema support (@octocat)

#### :bug: Bug Fix

- [#124](https://github.com/gleanwork/mcp-config/pull/124) fix: preserve default environment values (@octocat)
`,
      }),
      'lerna-changelog',
    );

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain('Add server URL schema support');
    expect(content).toContain('Preserve default environment values');
    expect(content).toContain('[PR #123]');
  });

  it('normalizes configure-mcp-server release-it changes', () => {
    const normalized = normalizeRelease(
      release({
        repo: 'configure-mcp-server',
        tag: 'v3.2.0',
        body: `#### Enhancement

- [#45](https://github.com/gleanwork/configure-mcp-server/pull/45) feat: add install flow for managed config

#### Bug Fix

- [#46](https://github.com/gleanwork/configure-mcp-server/pull/46) fix: avoid overwriting existing MCP server entries
`,
      }),
      'lerna-changelog',
    );

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain('Add install flow for managed config');
    expect(content).toContain('Avoid overwriting existing MCP server entries');
  });

  it('normalizes commitizen Python releases', () => {
    const normalized = normalizeRelease(
      release({
        repo: 'glean-indexing-sdk',
        tag: 'v1.0.0b2',
        category: 'Glean Indexing SDK',
        body: `## v1.0.0b2

### Feat

- add bulk indexing helpers (#14)

### Fix

- handle document retry errors (#15)
`,
      }),
      'commitizen',
    );

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain('Add bulk indexing helpers');
    expect(content).toContain('Handle document retry errors');
    expect(content).toContain('[PR #14]');
  });

  it('normalizes Speakeasy API client releases with structured changes', () => {
    const normalized = normalizeRelease(
      release({
        repo: 'api-client-go',
        tag: 'v0.11.40',
        category: 'API Clients',
        body: `# Generated by Speakeasy CLI

## Go SDK Changes:
* \`Glean.Client.Insights.Retrieve()\`:  \`response.AgentsResponse\` **Changed**
* \`Glean.Client.Search.RetrieveFeed()\`:  \`response.Results[].PrimaryEntry.PromptTemplate.FavoriteInfo.UgcType.Enum(spreadsheetType)\` **Added**
`,
      }),
      'speakeasy',
    );

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain('Changed `response.AgentsResponse`');
    expect(content).toContain('Added `response.Results[]');
  });

  it('marks empty Speakeasy releases as no-op', () => {
    const normalized = normalizeRelease(
      release({
        repo: 'api-client-typescript',
        tag: 'v0.14.19',
        category: 'API Clients',
        body: `# Generated by Speakeasy CLI

## 2026-04-20 17:34:02
### Changes
Based on:
- OpenAPI Doc 0.9.0
### Generated
- [typescript v0.14.19] .

Publishing Completed`,
      }),
      'speakeasy',
    );

    expect(normalized.isEmpty).toBe(true);
    expect(normalized.changes).toHaveLength(0);
  });

  it('does not mark routine configuration fixes as action required', () => {
    const normalized: NormalizedRelease = {
      release: release({
        repo: 'glean-indexing-sdk',
        tag: 'v1.0.0b2',
        category: 'Glean Indexing SDK',
      }),
      parser: 'commitizen',
      summary: 'Fixed datasource configuration handling.',
      changes: [
        {
          type: 'fixed',
          text: 'Fixed configure_datasource() to use attribute access and avoid camelCase keyword arguments.',
        },
      ],
      sourceRefs: [
        {
          label: 'Release notes',
          url: 'https://github.com/gleanwork/glean-indexing-sdk/releases/tag/v1.0.0b2',
        },
      ],
      warnings: [],
    };

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).not.toContain('## Action Required');
  });

  it('keeps legacy docs and internal bullets out of action required guidance', () => {
    const normalized = normalizeRelease(
      release({
        repo: 'configure-mcp-server',
        tag: 'v3.0.0',
        body: `Minimum supported Node.js version is now 22 LTS.

## Breaking Changes

- Breaking: Node.js 22 LTS is now required.
- Documentation: Added GA stability badge to README.
- Internal: Migrated build tooling.
`,
      }),
      'legacy',
    );

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain(
      '- Verify your runtime uses Node.js 22 or later.',
    );
    expect(content).not.toContain(
      'Review this breaking change before upgrading: Documentation',
    );
    expect(content).not.toContain('Follow the migration notes');
  });

  it('adds runtime guidance for legacy minimum Go version changes', () => {
    const normalized = normalizeRelease(
      release({
        repo: 'api-client-go',
        tag: 'v0.6.0',
        category: 'SDK',
        body: `**Breaking Changes:** Updated minimum go version to 1.22 (from 1.20).

## Changes

- **Breaking Changes:** Updated minimum go version to 1.22 (from 1.20).
`,
      }),
      'legacy',
    );

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain('## Action Required');
    expect(content).toContain('- Verify your Go toolchain uses 1.22 or later.');
    expect(content).toContain('## Breaking Changes');
  });

  it('renders OpenAPI changes with normalized section ordering', () => {
    const normalized: NormalizedRelease = {
      release: release({
        repo: 'open-api',
        tag: '2025-12-04',
        category: 'API',
      }),
      parser: 'openapi',
      summary: 'Breaking change: removed legacy client endpoint.',
      changes: [
        { type: 'added', text: 'Added endpoint GET /rest/api/v1/tools' },
        { type: 'breaking', text: 'Removed endpoint DELETE /rest/api/v1/old' },
      ],
      sourceRefs: [
        {
          label: 'open-api abc1234',
          url: 'https://github.com/gleanwork/open-api/commit/abc1234',
        },
      ],
      warnings: [],
    };

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain('## Action Required');
    expect(content).toContain(
      '- Update callers to stop using DELETE /rest/api/v1/old.',
    );
    expect(content.indexOf('## Action Required')).toBeLessThan(
      content.indexOf('## Changes'),
    );
    expect(content.indexOf('## Changes')).toBeLessThan(
      content.indexOf('## Breaking Changes'),
    );
    expect(content.indexOf('## Breaking Changes')).toBeLessThan(
      content.indexOf('## Source'),
    );
  });

  it('renders deprecated changes in a dedicated section with migration guidance', () => {
    const normalized: NormalizedRelease = {
      release: release({
        repo: 'api-client-python',
        tag: 'v0.12.4',
        category: 'API Clients',
      }),
      parser: 'speakeasy',
      summary: 'Deprecated legacy metadata field.',
      changes: [
        {
          type: 'deprecated',
          text: 'Deprecated `request.metadata.legacyId` on `client.documents.index()`',
        },
      ],
      sourceRefs: [
        {
          label: 'Release notes',
          url: 'https://github.com/gleanwork/api-client-python/releases/tag/v0.12.4',
        },
      ],
      warnings: [],
    };

    const content = renderEntry(normalized);
    expectNormalizedEntry(content);
    expect(content).toContain('## Action Required');
    expect(content).toContain(
      '- Plan migration away from `request.metadata.legacyId` on `client.documents.index()`.',
    );
    expect(content).toContain('## Deprecated');
    expect(content.indexOf('## Changes')).toBeLessThan(
      content.indexOf('## Deprecated'),
    );
    expect(content.indexOf('## Deprecated')).toBeLessThan(
      content.indexOf('## Source'),
    );
  });
});
