import { describe, it, expect, vi, beforeEach } from 'vitest';
import type { Octokit } from 'octokit';
import { fetchNewReleases } from '../release-fetcher.js';
import type { RepoReleases } from '../octo.js';

vi.mock('../octo.js', () => ({
  listReleases: vi.fn(),
}));

const { listReleases } = await import('../octo.js');
const mockListReleases = vi.mocked(listReleases);

const fakeOctokit = {} as Octokit;
const spec = {
  owner: 'gleanwork',
  repo: 'api-client-go',
  category: 'API Clients',
};

function makeRelease(tag: string, publishedAt: string | null) {
  return {
    tag_name: tag,
    published_at: publishedAt,
    html_url: `https://github.com/gleanwork/api-client-go/releases/tag/${tag}`,
    url: '',
    body: `# Generated by Speakeasy CLI\n## Go SDK Changes:\n* \`Glean.Client.Foo()\`: \`bar\` **Added**`,
  } as unknown as RepoReleases[number];
}

describe('fetchNewReleases', () => {
  beforeEach(() => {
    mockListReleases.mockReset();
  });

  it('throws when listReleases returns an empty array (transient API failure)', async () => {
    mockListReleases.mockResolvedValue([] as RepoReleases);

    await expect(
      fetchNewReleases(fakeOctokit, spec, '2026-04-13'),
    ).rejects.toThrow(
      /listReleases returned zero dated releases for gleanwork\/api-client-go/,
    );
  });

  it('throws when listReleases returns only undated releases', async () => {
    mockListReleases.mockResolvedValue([
      makeRelease('v0.1.0', null),
    ] as RepoReleases);

    await expect(
      fetchNewReleases(fakeOctokit, spec, '2026-04-13'),
    ).rejects.toThrow(/zero dated releases/);
  });

  it('returns empty status (not an error) when all releases are older than cutoff', async () => {
    mockListReleases.mockResolvedValue([
      makeRelease('v0.11.40', '2026-04-09T16:27:34Z'),
      makeRelease('v0.11.41', '2026-04-13T17:36:41Z'),
    ] as RepoReleases);

    const result = await fetchNewReleases(fakeOctokit, spec, '2026-04-13');

    expect(result.status).toBe('empty');
    if (result.status === 'empty') {
      expect(result.reason).toBe('no newer release than latest entry');
    }
  });

  it('returns newer releases when cutoff is passed', async () => {
    mockListReleases.mockResolvedValue([
      makeRelease('v0.11.42', '2026-04-15T21:46:40Z'),
      makeRelease('v0.11.41', '2026-04-13T17:36:41Z'),
    ] as RepoReleases);

    const result = await fetchNewReleases(fakeOctokit, spec, '2026-04-13');

    expect(result.status).toBe('ok');
    if (result.status === 'ok') {
      expect(result.releases).toHaveLength(1);
      expect(result.releases[0].tag).toBe('v0.11.42');
      expect(result.releases[0].publishedAt).toBe('2026-04-15');
    }
  });

  it('returns all releases when cutoff is null', async () => {
    mockListReleases.mockResolvedValue([
      makeRelease('v0.11.42', '2026-04-15T21:46:40Z'),
      makeRelease('v0.11.41', '2026-04-13T17:36:41Z'),
    ] as RepoReleases);

    const result = await fetchNewReleases(fakeOctokit, spec, null);

    expect(result.status).toBe('ok');
    if (result.status === 'ok') {
      expect(result.releases).toHaveLength(2);
    }
  });
});
