import type { ParsedChange } from '../types.js';

/**
 * Detect if release notes are in Speakeasy CLI format.
 * Matches both releases with SDK changes (method/field patterns)
 * and empty releases (version bumps with no API changes).
 */
export function isSpeakeasyFormat(text: string): boolean {
  return /^#\s*Generated by Speakeasy/m.test(text);
}

/**
 * Parse Speakeasy release notes into structured changes.
 *
 * Handles two patterns:
 * 1. Single-line: * `Method()`:  `field.path` **Action**
 * 2. Multi-line:  * `Method()`:
 *                   *  `field.path` **Action**
 */
export function parseSpeakeasyNotes(text: string): ParsedChange[] {
  const changes: ParsedChange[] = [];
  const lines = text.split('\n');
  let currentMethod = '';

  for (const line of lines) {
    // Match method header: * `Glean.Client.Chat.Create()`:
    const methodMatch = line.match(/^\*\s+`([^`]+\(\))`[:\s]*$/);
    if (methodMatch) {
      currentMethod = methodMatch[1];
      continue;
    }

    // Match single-line change: * `Method()`:  `field` **Action**
    const singleLineMatch = line.match(
      /^\*\s+`([^`]+\(\))`:\s+`([^`]+)`\s+\*\*(Added|Removed|Changed|Deprecated)\*\*/i,
    );
    if (singleLineMatch) {
      changes.push({
        method: singleLineMatch[1],
        field: singleLineMatch[2],
        action: singleLineMatch[3].toLowerCase() as ParsedChange['action'],
      });
      continue;
    }

    // Match indented change under current method:   *  `field` **Action**
    const indentedMatch = line.match(
      /^\s+\*\s+`([^`]+)`\s+\*\*(Added|Removed|Changed|Deprecated)\*\*/i,
    );
    if (indentedMatch && currentMethod) {
      changes.push({
        method: currentMethod,
        field: indentedMatch[1],
        action: indentedMatch[2].toLowerCase() as ParsedChange['action'],
      });
      continue;
    }

    // Non-matching line resets method context (unless blank)
    if (
      line.trim() &&
      !line.startsWith('#') &&
      !line.startsWith('[') &&
      !/speakeasy|publishing/i.test(line)
    ) {
      currentMethod = '';
    }
  }

  return changes;
}

function simplifyFieldPath(field: string): string {
  const enumMatch = field.match(/\.enum\((\w+)\)$/i);
  if (enumMatch) {
    return enumMatch[1];
  }

  const segments = field.split('.');
  const last = segments[segments.length - 1]
    .replace(/\[\]/g, '')
    .replace(/Map<\w+>/g, '');
  return last;
}

function shortMethodName(method: string): string {
  // Strip the leading "Glean." namespace but preserve everything else,
  // so we keep meaningful paths like "client.insights.retrieve()" or
  // "governance.createfindingsexport()".
  return method.replace(/^[Gg]lean\./, '').toLowerCase();
}

function joinList(items: string[]): string {
  if (items.length === 0) return '';
  if (items.length === 1) return items[0];
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`;
}

const VERBS: Array<{
  action: ParsedChange['action'];
  verb: string;
  preposition: string;
}> = [
  { action: 'added', verb: 'Added', preposition: 'to' },
  { action: 'removed', verb: 'Removed', preposition: 'from' },
  { action: 'changed', verb: 'Changed', preposition: 'on' },
  { action: 'deprecated', verb: 'Deprecated', preposition: 'on' },
];

/**
 * Format parsed Speakeasy changes into prose: one sentence per action verb,
 * with backticked field and method names. Deterministic — only emits
 * identifiers that appear in the parsed changes.
 */
export function formatSpeakeasySummary(
  changes: ParsedChange[],
  opts: { maxBullets?: number; maxChars?: number } = {},
): string {
  if (changes.length === 0) {
    return 'Maintenance updates and improvements.';
  }

  const maxChars = opts.maxChars ?? 300;
  const itemsPerVerb = Math.max(1, opts.maxBullets ?? 4);

  const sentences: string[] = [];
  for (const { action, verb, preposition } of VERBS) {
    const items = changes.filter((c) => c.action === action);
    if (items.length === 0) continue;

    const phrases = items.slice(0, itemsPerVerb).map((c) => {
      const field = simplifyFieldPath(c.field);
      const method = shortMethodName(c.method);
      return `\`${field}\` ${preposition} \`${method}\``;
    });

    const overflow = items.length - itemsPerVerb;
    const tail = overflow > 0 ? ` and ${overflow} more` : '';
    sentences.push(`${verb} ${joinList(phrases)}${tail}.`);
  }

  let result = sentences.join(' ');

  if (result.length > maxChars) {
    result =
      result
        .slice(0, maxChars - 3)
        .replace(/\s+\S*$/, '')
        .trim() + '...';
  }

  return result;
}
