import type { ParsedChange } from '../types.js';

/**
 * Detect if release notes are in Speakeasy CLI format.
 * Matches both releases with SDK changes (method/field patterns)
 * and empty releases (version bumps with no API changes).
 */
export function isSpeakeasyFormat(text: string): boolean {
  return /^#\s*Generated by Speakeasy/m.test(text);
}

/**
 * Parse Speakeasy release notes into structured changes.
 *
 * Handles two patterns:
 * 1. Single-line: * `Method()`:  `field.path` **Action**
 * 2. Multi-line:  * `Method()`:
 *                   *  `field.path` **Action**
 */
export function parseSpeakeasyNotes(text: string): ParsedChange[] {
  const changes: ParsedChange[] = [];
  const lines = text.split('\n');
  let currentMethod = '';

  for (const line of lines) {
    // Match method header: * `Glean.Client.Chat.Create()`:
    const methodMatch = line.match(/^\*\s+`([^`]+\(\))`[:\s]*$/);
    if (methodMatch) {
      currentMethod = methodMatch[1];
      continue;
    }

    // Match single-line change: * `Method()`:  `field` **Action**
    const singleLineMatch = line.match(
      /^\*\s+`([^`]+\(\))`:\s+`([^`]+)`\s+\*\*(Added|Removed|Changed|Deprecated)\*\*/i,
    );
    if (singleLineMatch) {
      changes.push({
        method: singleLineMatch[1],
        field: singleLineMatch[2],
        action: singleLineMatch[3].toLowerCase() as ParsedChange['action'],
      });
      continue;
    }

    // Match indented change under current method:   *  `field` **Action**
    const indentedMatch = line.match(
      /^\s+\*\s+`([^`]+)`\s+\*\*(Added|Removed|Changed|Deprecated)\*\*/i,
    );
    if (indentedMatch && currentMethod) {
      changes.push({
        method: currentMethod,
        field: indentedMatch[1],
        action: indentedMatch[2].toLowerCase() as ParsedChange['action'],
      });
      continue;
    }

    // Non-matching line resets method context (unless blank)
    if (
      line.trim() &&
      !line.startsWith('#') &&
      !line.startsWith('[') &&
      !/speakeasy|publishing/i.test(line)
    ) {
      currentMethod = '';
    }
  }

  return changes;
}

/**
 * Simplify a deep field path for human-readable summary.
 * e.g. "request.chatRequest.messages[].citations[].sourceFile.metadata.status.enum(partiallyProcessed)"
 *   -> "partiallyProcessed"
 *
 * But for simple paths: "request.document.nativeAppUrl" -> "nativeAppUrl"
 */
function simplifyFieldPath(field: string): string {
  // Extract enum value if present: .enum(value) -> "value enum"
  const enumMatch = field.match(/\.enum\((\w+)\)$/);
  if (enumMatch) {
    return enumMatch[1];
  }

  // Get the last meaningful segment
  const segments = field.split('.');
  const last = segments[segments.length - 1]
    .replace(/\[\]/g, '')
    .replace(/Map<\w+>/g, '');
  return last;
}

/**
 * Extract a short method name from the full SDK path.
 * e.g. "Glean.Client.Chat.Create()" -> "chat create"
 * e.g. "glean.client.chat.create()" -> "chat create"
 * e.g. "Glean.Governance.Createfindingsexport()" -> "governance createfindingsexport"
 */
function shortMethodName(method: string): string {
  const parts = method.replace(/\(\)$/, '').split('.');
  // Skip "Glean"/"glean" and "Client"/"client" prefixes
  const meaningful = parts.filter((p) => !/^(glean|client)$/i.test(p));
  return meaningful.join(' ').toLowerCase();
}

/**
 * Format parsed Speakeasy changes into a human-readable summary
 * matching the repo's established entry format.
 */
export function formatSpeakeasySummary(
  changes: ParsedChange[],
  opts: { maxBullets?: number; maxChars?: number } = {},
): string {
  if (changes.length === 0) {
    return 'Maintenance updates and improvements.';
  }

  const maxBullets = opts.maxBullets ?? 3;
  const maxChars = opts.maxChars ?? 300;

  // Group changes by action type
  const byAction = new Map<string, ParsedChange[]>();
  for (const c of changes) {
    const existing = byAction.get(c.action) || [];
    existing.push(c);
    byAction.set(c.action, existing);
  }

  // Group changes by simplified method for the intro
  const methodNames = new Set(changes.map((c) => shortMethodName(c.method)));
  const methodList = [...methodNames].slice(0, 4);
  const methodSuffix =
    methodNames.size > 4 ? ` and ${methodNames.size - 4} more` : '';

  // Build intro sentence
  const actionCounts: string[] = [];
  for (const [action, items] of byAction) {
    actionCounts.push(
      `${items.length} field${items.length > 1 ? 's' : ''} ${action}`,
    );
  }

  const intro = `${actionCounts.join(', ')} across ${methodList.join(', ')}${methodSuffix} endpoints.`;

  // Build detail bullets (up to maxBullets) using ` - ` separator format
  const details: string[] = [];
  for (const c of changes.slice(0, maxBullets)) {
    const fieldName = simplifyFieldPath(c.field);
    const method = shortMethodName(c.method);
    details.push(`${c.action} ${fieldName} in ${method}`);
  }

  let result = details.length > 0 ? intro + ' - ' + details.join(' - ') : intro;

  // Capitalize first letter
  result = result.charAt(0).toUpperCase() + result.slice(1);

  // Truncate if needed
  if (result.length > maxChars) {
    result =
      result
        .slice(0, maxChars)
        .replace(/\s+\S*$/, '')
        .trim() + '...';
  }

  return result;
}
