import { describe, it, expect } from 'vitest';
import {
  isSpeakeasyFormat,
  parseSpeakeasyNotes,
  formatSpeakeasySummary,
} from '../speakeasy.js';

const FIXTURE_GO_v0_11_41 = `# Generated by Speakeasy CLI
[github.com/gleanwork/api-client-go 0.11.41](https://github.com/gleanwork/api-client-go/releases/tag/v0.11.41)
## Go SDK Changes:
* \`Glean.Client.Search.RetrieveFeed()\`:  \`response.Results[].PrimaryEntry.Workflow.Workflow.LastDraftSavedAt\` **Added**
* \`Glean.Governance.Createfindingsexport()\`:
  *  \`request.Request.Filter.Statuses\` **Added**
  *  \`response.Filter.Statuses\` **Added**
* \`Glean.Governance.Listfindingsexports()\`:  \`response.Exports[].Filter.Statuses\` **Added**

Generated with [Speakeasy CLI 1.761.3](https://github.com/speakeasy-api/speakeasy/releases)`;

const FIXTURE_GO_v0_11_40 = `# Generated by Speakeasy CLI
[github.com/gleanwork/api-client-go 0.11.40](https://github.com/gleanwork/api-client-go/releases/tag/v0.11.40)
## Go SDK Changes:
* \`Glean.Client.Insights.Retrieve()\`:  \`response.AgentsResponse\` **Changed**
* \`Glean.Client.Search.RetrieveFeed()\`:  \`response.Results[].PrimaryEntry.PromptTemplate.FavoriteInfo.UgcType.Enum(spreadsheetType)\` **Added**

Generated with [Speakeasy CLI 1.761.1](https://github.com/speakeasy-api/speakeasy/releases)`;

const FIXTURE_GO_v0_11_25 = `# Generated by Speakeasy CLI
[github.com/gleanwork/api-client-go 0.11.25](https://github.com/gleanwork/api-client-go/releases/tag/v0.11.25)
## Go SDK Changes:
* \`Glean.Client.Activity.Feedback()\`:
  *  \`request.Feedback1.Event.Enum(feedbackTimeSaved)\` **Added**

Generated with [Speakeasy CLI 1.709.3](https://github.com/speakeasy-api/speakeasy/releases)`;

const FIXTURE_TS_v0_14_14 = `# Generated by Speakeasy CLI
[@gleanwork/api-client 0.14.14](https://www.npmjs.com/package/@gleanwork/api-client/v/0.14.14)
## Typescript SDK Changes:
* \`glean.client.chat.create()\`:
  *  \`request.chatRequest.messages[].citations[].sourceFile.metadata.status.enum(partiallyProcessed)\` **Added**
  *  \`response.messages[].citations[].sourceFile.metadata.status.enum(partiallyProcessed)\` **Added**
* \`glean.client.chat.retrieve()\`:  \`response.chatResult.chat.messages[].citations[].sourceFile.metadata.status.enum(partiallyProcessed)\` **Added**
* \`glean.client.chat.uploadFiles()\`:  \`response.files[].metadata.status.enum(partiallyProcessed)\` **Added**
* \`glean.client.chat.retrieveFiles()\`:  \`response.files.Map<ChatFile>.metadata.status.enum(partiallyProcessed)\` **Added**
* \`glean.client.chat.createStream()\`:
  *  \`request.chatRequest.messages[].citations[].sourceFile.metadata.status.enum(partiallyProcessed)\` **Added**
* \`glean.indexing.documents.addOrUpdate()\`:
  *  \`request.document.nativeAppUrl\` **Added**
* \`glean.indexing.documents.index()\`:
  *  \`request.documents[].nativeAppUrl\` **Added**
* \`glean.indexing.documents.bulkIndex()\`:
  *  \`request.documents[].nativeAppUrl\` **Added**

Generated with [Speakeasy CLI 1.759.3](https://github.com/speakeasy-api/speakeasy/releases)

Publishing Completed`;

const FIXTURE_EMPTY_SPEAKEASY = `# Generated by Speakeasy CLI

## 2026-04-20 17:34:02
### Changes
Based on:
- OpenAPI Doc 0.9.0
- Speakeasy CLI 1.761.8 (2.881.2) https://github.com/speakeasy-api/speakeasy
### Generated
- [typescript v0.14.19] .
### Releases
- [NPM v0.14.19] https://www.npmjs.com/package/@gleanwork/api-client/v/0.14.19 - .

Publishing Completed`;

const FIXTURE_NOT_SPEAKEASY = `## What's Changed
* Add installable skills for SDK usage
* Add injectable GleanContext
* Support LangGraph 1.x

**Full Changelog**: https://github.com/gleanwork/glean-agent-toolkit/compare/0.4.0...0.5.0`;

describe('isSpeakeasyFormat', () => {
  it('returns true for Go v0.11.41 (multi-method, mixed nesting)', () => {
    expect(isSpeakeasyFormat(FIXTURE_GO_v0_11_41)).toBe(true);
  });

  it('returns true for Go v0.11.40 (simple, two changes)', () => {
    expect(isSpeakeasyFormat(FIXTURE_GO_v0_11_40)).toBe(true);
  });

  it('returns true for Go v0.11.25 (minimal, one change)', () => {
    expect(isSpeakeasyFormat(FIXTURE_GO_v0_11_25)).toBe(true);
  });

  it('returns true for TypeScript v0.14.14 (many changes)', () => {
    expect(isSpeakeasyFormat(FIXTURE_TS_v0_14_14)).toBe(true);
  });

  it('returns false for non-Speakeasy release notes', () => {
    expect(isSpeakeasyFormat(FIXTURE_NOT_SPEAKEASY)).toBe(false);
  });

  it('returns false for empty string', () => {
    expect(isSpeakeasyFormat('')).toBe(false);
  });

  it('returns false for plain text with no structure', () => {
    expect(isSpeakeasyFormat('Just some plain text about a release.')).toBe(
      false,
    );
  });

  it('returns true for empty Speakeasy releases (Publishing Completed only)', () => {
    expect(isSpeakeasyFormat(FIXTURE_EMPTY_SPEAKEASY)).toBe(true);
  });
});

describe('parseSpeakeasyNotes', () => {
  it('parses Go v0.11.41 into 4 changes', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_41);
    expect(changes).toHaveLength(4);

    expect(changes[0]).toEqual({
      method: 'Glean.Client.Search.RetrieveFeed()',
      field:
        'response.Results[].PrimaryEntry.Workflow.Workflow.LastDraftSavedAt',
      action: 'added',
    });

    expect(changes[1]).toEqual({
      method: 'Glean.Governance.Createfindingsexport()',
      field: 'request.Request.Filter.Statuses',
      action: 'added',
    });

    expect(changes[2]).toEqual({
      method: 'Glean.Governance.Createfindingsexport()',
      field: 'response.Filter.Statuses',
      action: 'added',
    });

    expect(changes[3]).toEqual({
      method: 'Glean.Governance.Listfindingsexports()',
      field: 'response.Exports[].Filter.Statuses',
      action: 'added',
    });
  });

  it('parses Go v0.11.40 into 2 changes (1 changed, 1 added)', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_40);
    expect(changes).toHaveLength(2);

    expect(changes[0]).toEqual({
      method: 'Glean.Client.Insights.Retrieve()',
      field: 'response.AgentsResponse',
      action: 'changed',
    });

    expect(changes[1]).toEqual({
      method: 'Glean.Client.Search.RetrieveFeed()',
      field:
        'response.Results[].PrimaryEntry.PromptTemplate.FavoriteInfo.UgcType.Enum(spreadsheetType)',
      action: 'added',
    });
  });

  it('parses Go v0.11.25 into 1 change', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_25);
    expect(changes).toHaveLength(1);

    expect(changes[0]).toEqual({
      method: 'Glean.Client.Activity.Feedback()',
      field: 'request.Feedback1.Event.Enum(feedbackTimeSaved)',
      action: 'added',
    });
  });

  it('parses TypeScript v0.14.14 into 9 changes', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_TS_v0_14_14);
    expect(changes).toHaveLength(9);

    // Spot-check a few
    expect(changes[0]).toEqual({
      method: 'glean.client.chat.create()',
      field:
        'request.chatRequest.messages[].citations[].sourceFile.metadata.status.enum(partiallyProcessed)',
      action: 'added',
    });

    expect(changes[4]).toEqual({
      method: 'glean.client.chat.retrieveFiles()',
      field:
        'response.files.Map<ChatFile>.metadata.status.enum(partiallyProcessed)',
      action: 'added',
    });

    // Last change: bulkIndex nativeAppUrl
    expect(changes[8]).toEqual({
      method: 'glean.indexing.documents.bulkIndex()',
      field: 'request.documents[].nativeAppUrl',
      action: 'added',
    });
  });

  it('returns no changes for empty Speakeasy releases (signal for pipeline skip)', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_EMPTY_SPEAKEASY);
    expect(changes).toHaveLength(0);
  });

  it('returns correct method and action for each change', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_40);

    for (const change of changes) {
      expect(change.method).toBeTruthy();
      expect(change.field).toBeTruthy();
      expect(['added', 'removed', 'changed', 'deprecated']).toContain(
        change.action,
      );
    }
  });
});

describe('formatSpeakeasySummary', () => {
  it('returns fallback text for empty changes array', () => {
    const result = formatSpeakeasySummary([]);
    expect(result).toBe('Maintenance updates and improvements.');
  });

  it('produces prose with no markdown bullets', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_41);
    const result = formatSpeakeasySummary(changes);

    for (const line of result.split('\n')) {
      expect(line).not.toMatch(/^- /);
    }
  });

  it('groups changes by action verb into one sentence each', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_40);
    const result = formatSpeakeasySummary(changes);

    // FIXTURE_GO_v0_11_40 has one 'changed' and one 'added'
    expect(result).toMatch(/^Added\b/);
    expect(result).toContain('Changed ');
  });

  it('backticks both field and method names', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_41);
    const result = formatSpeakeasySummary(changes);

    // Each phrase should look like `field` to|from|on `method`
    expect(result).toMatch(/`[A-Za-z]+`\s+(to|from|on)\s+`[a-z.()]+`/);
  });

  it('preserves dotted method paths', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_41);
    const result = formatSpeakeasySummary(changes);

    // "Glean.Governance.Createfindingsexport()" -> "governance.createfindingsexport()"
    expect(result).toContain('governance.createfindingsexport()');
    expect(result).toContain('governance.listfindingsexports()');
  });

  it('mentions actual field/method names from the changes', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_GO_v0_11_40);
    const result = formatSpeakeasySummary(changes);

    expect(result.toLowerCase()).toMatch(
      /insights|retrieve|search|retrievefeed|agentsresponse|spreadsheettype/,
    );
  });

  it('respects maxChars', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_TS_v0_14_14);
    const result = formatSpeakeasySummary(changes, { maxChars: 100 });
    expect(result.length).toBeLessThanOrEqual(100);
  });

  it('produces meaningful output for TypeScript fixture', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_TS_v0_14_14);
    const result = formatSpeakeasySummary(changes);

    expect(result.length).toBeGreaterThan(20);
    expect(result[0]).toMatch(/[A-Z]/);
    expect(result.endsWith('.') || result.endsWith('...')).toBe(true);
  });

  it('caps items per verb with "and N more" when there are many changes', () => {
    const changes = parseSpeakeasyNotes(FIXTURE_TS_v0_14_14);
    // FIXTURE_TS_v0_14_14 has 9 'added' changes, default cap is 4
    const result = formatSpeakeasySummary(changes, {
      maxBullets: 4,
      maxChars: 1000,
    });
    expect(result).toMatch(/and \d+ more/);
  });
});
