/**
 * Endpoint metadata table for API reference pages: endpoint, release stage,
 * release version (once specs carry it), authorization, scopes, and field
 * deprecations. Replaces the method/path line, the deprecated/beta/
 * experimental banners, and the right-panel Authorization summary.
 * Props are generated by scripts/generator/endpointMetadata.ts.
 */
import React, { type ReactNode } from 'react';
import MethodEndpoint from '@theme/ApiExplorer/MethodEndpoint';
import type { EndpointMetadataData } from '@site/src/types/endpointMetadata';
import {
  AuthSummary,
  FieldDeprecations,
  ScopeList,
  StageBadge,
  StageDetails,
  StageNotice,
} from './parts';
import styles from './styles.module.css';

export default function EndpointMetadata({
  metadata,
}: {
  metadata: EndpointMetadataData;
}): ReactNode {
  const { release, authorization, scopes, deprecations } = metadata;
  const fieldDeprecations = deprecations.filter((d) => d.type !== 'endpoint');
  return (
    <section className={styles.metadata}>
      <dl className={styles.table}>
        <dt>Endpoint</dt>
        <dd className={styles.endpoint}>
          <MethodEndpoint
            method={metadata.method}
            path={metadata.path}
            context="endpoint"
          />
        </dd>
        <dt>Release stage</dt>
        <dd>
          <span className={styles.inlineRow}>
            <StageBadge stage={release.stage} />
            <StageDetails release={release} />
          </span>
          <StageNotice release={release} />
        </dd>
        {release.version && (
          <>
            <dt>Release version</dt>
            <dd>
              <code>{release.version}</code>
            </dd>
          </>
        )}
        {authorization && (
          <>
            <dt>Authorization</dt>
            <dd>
              <AuthSummary auth={authorization} />
            </dd>
          </>
        )}
        {scopes?.legacy && (
          <>
            <dt>Scopes</dt>
            <dd>
              <ScopeList scopes={scopes.legacy} />
            </dd>
          </>
        )}
        {fieldDeprecations.length > 0 && (
          <>
            <dt>Deprecations</dt>
            <dd>
              <FieldDeprecations items={fieldDeprecations} />
            </dd>
          </>
        )}
      </dl>
    </section>
  );
}
