import { z } from 'zod';

/**
 * Developer videos registry (`src/data/videos.json`).
 *
 * Generated by `pnpm videos:sync` from gleanwork/glean-developer-videos, which
 * owns each video's metadata and media. Don't edit the JSON by hand.
 *
 * Videos are a format, not a section: each one is attached to the page it
 * explains (`related.doc`) and plays there. `/videos` only collects them.
 */

export const VIDEO_TYPES = ['explainer', 'walkthrough', 'recipe'] as const;
export type VideoType = (typeof VIDEO_TYPES)[number];

export const VIDEO_TYPE_LABELS: Record<VideoType, string> = {
  explainer: 'Explainer',
  walkthrough: 'Walkthrough',
  recipe: 'Recipe walkthrough',
};

export const VIDEO_VISIBILITIES = ['public', 'preview'] as const;

/** Labels match `PLATFORM_CAPABILITIES` in `src/components/home/platformStatus.ts`. */
export const VIDEO_PLATFORM_CAPABILITIES = [
  'Search',
  'Chat',
  'Agents',
  'Skills',
  'Triggers',
] as const;

const stage = z.enum(['ga', 'experimental']);

export const videoTrackSchema = z.strictObject({
  id: z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/),
  label: z.string().min(1),
  description: z.string().min(1),
});

export const videoSchema = z.strictObject({
  id: z
    .string()
    .regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, 'id must be a kebab-case slug'),
  title: z.string().min(1),
  /** One or two lines on a card. */
  summary: z.string().min(1).max(160),
  track: z.string().min(1),
  /** Authored episode order. A series can span tracks. */
  series: z
    .strictObject({
      id: z.string().min(1),
      label: z.string().min(1),
      position: z.number().int().positive(),
    })
    .optional(),
  type: z.enum(VIDEO_TYPES),
  /**
   * The lifecycle stage each capability has *in the video* (narration and
   * burned-in labels). Public videos must agree with the docs; see tests.
   */
  narratedStages: z
    .partialRecord(z.enum(VIDEO_PLATFORM_CAPABILITIES), stage)
    .optional(),
  /**
   * `preview` videos show only with the `preview-content` flag. They still ship
   * in the build (hidden, not secret). See `src/lib/previewContent.ts`.
   */
  visibility: z.enum(VIDEO_VISIBILITIES),
  /** Why a video is held back. Shown to reviewers only. */
  previewReason: z.string().min(1).optional(),
  /** Lower is preferred for the "Start here" slot; the first available wins. */
  featured: z.number().int().positive().optional(),
  durationSeconds: z.number().int().positive(),
  /** Accepted render number in glean-developer-videos (its versions.json). */
  version: z.number().int().positive().optional(),
  updated: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  languages: z.array(z.string().min(1)).max(2).optional(),
  related: z.strictObject({
    /** Canonical page the video explains; it plays there. */
    doc: z.string().min(1),
    /** Doc id for `doc` when it lives on this site (validated in tests). */
    docId: z.string().min(1).optional(),
    docLabel: z.string().min(1),
    /** Cookbook recipe id; the recipe banner plays this video. */
    recipe: z.string().min(1).optional(),
  }),
  media: z.strictObject({
    src: z.string().min(1),
    poster: z.string().min(1),
    width: z.number().int().positive(),
    height: z.number().int().positive(),
  }),
  /** One paragraph per scene, written for reading (URLs as written). */
  transcript: z.array(z.string().min(1)).min(1),
});

export const videosFileSchema = z.strictObject({
  tracks: z.array(videoTrackSchema).min(1),
  videos: z.array(videoSchema),
});

export type VideoRecord = z.infer<typeof videoSchema>;
export type VideoTrack = z.infer<typeof videoTrackSchema>;
export type VideosFile = z.infer<typeof videosFileSchema>;
