import { describe, it, expect } from 'vitest';
import { summarizeRelease } from '../src/summarizer';

describe('summarizer (heuristic)', () => {
  it('produces intro + bullets within maxChars', async () => {
    const text = `Generated by Speakeasy CLI\n\n- Added: New endpoint /v1/foo\n- Fixed: Bug in /v1/bar\n`;
    const out = await summarizeRelease(text, {
      mode: 'heuristic',
      maxBullets: 3,
      maxChars: 120,
    });
    expect(out.length).toBeGreaterThan(0);
    expect(out.length).toBeLessThanOrEqual(120 + 3);
    expect(out).not.toMatch(/Speakeasy/i);
  });
});

describe('summarizer', () => {
  const SAMPLE = `
  # v1.2.3
  
  ### Added
  - New endpoint for listing widgets with pagination.
  - Support for OAuth device flow.
  
  ### Fixed
  - Handle 429 retry logic in the client.
  
  For details see https://github.com/org/repo/releases/tag/v1.2.3
  `;

  it('returns a concise heuristic summary string', async () => {
    const res = await summarizeRelease(SAMPLE, {
      mode: 'heuristic',
      maxBullets: 3,
      maxChars: 300,
    });
    expect(typeof res).toBe('string');
    expect(res.length).toBeGreaterThan(0);
  });
});
