openapi: '3.0.0'
info:
  title: 'Jira Create Ticket'
  version: '1.0.0'
servers:
  - url: 'https://{YOUR-ATLASSIAN-DOMAIN}.atlassian.net/secure/CreateIssueDetails!init.jspa?'
paths:
  /:
    post:
      summary: 'Creates an issue or a sub-task from a JSON representation'
      description: |
        This API allows you to create a ticket or an issue in Jira.
      parameters:
        - name: 'pid'
          in: 'query'
          required: true
          schema:
            type: 'string'
            x-glean-typehint: 'JiraProjectID'
            default: '10000'
          description: 'Project ID where the ticket is created. 10000 refers to Engineering project.'
        - name: 'issuetype'
          in: 'query'
          required: true
          schema:
            type: 'integer'
            enum:
              - 10002
              - 10004
          description: 'Issue type. 10002 refers to Task, 10004 refers to Bug.'
        - name: 'priority'
          in: 'query'
          schema:
            type: 'integer'
            minimum: 1
            maximum: 5
          description: 'Numeric priority. 1 (highest) to 5 (lowest).'
        - name: 'summary'
          in: 'query'
          required: true
          schema:
            type: 'string'
            x-glean-typehint: 'Content'
          description: 'Title of the issue.'
        - name: 'components'
          in: 'query'
          schema:
            type: 'string'
            x-glean-typehint: 'JiraComponent'
          description: 'Component name where the ticket should be filed.'
        - name: 'description'
          in: 'query'
          schema:
            type: 'string'
            x-glean-typehint: 'Content'
          description: 'Body of the issue.'
        - name: 'assignee'
          in: 'query'
          schema:
            type: 'string'
            x-glean-typehint: 'JiraId'
          description: 'User to which the issue is assigned.'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: 'string'
